using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi;
using System;

namespace Nexora.Api.Extensions;

/// <summary>
/// Responsibility: Configures Swagger/OpenAPI generation services.
/// This isolates the setup for API documentation and UI testing endpoints.
/// </summary>
public static class SwaggerServiceExtensions
{
    public static IServiceCollection AddSwaggerServices(this IServiceCollection services)
    {
        services.AddSwaggerGen(options =>
        {
            options.SwaggerDoc("v1", new OpenApiInfo { Title = "Nexora API", Version = "v1" });

            // Include XML documentation comments from all compiled module assemblies
            // This reads the XML files generated by the compiler if <GenerateDocumentationFile> is true.
            var xmlFiles = System.IO.Directory.GetFiles(AppContext.BaseDirectory, "*.xml");
            foreach (var xmlPath in xmlFiles)
            {
                options.IncludeXmlComments(xmlPath);
            }

            // AddSecurityDefinition("Bearer", ...): This tells Swagger to use JWT Bearer authentication 
            // and displays the "Authorize" button at the top of the Swagger UI page.
            options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
            {
                Name = "Authorization",
                Description = "Enter 'Bearer {your_keycloak_token}'. Obtain it from your Keycloak instance.",
                In = ParameterLocation.Header,
                Type = SecuritySchemeType.ApiKey,
                Scheme = "Bearer",
                BearerFormat = "JWT"
            });

            // AddSecurityRequirement(...): This applies the security definition globally, so whenever you 
            // execute a request from Swagger UI, it will automatically attach the Authorization: Bearer <token> header for you.
            options.AddSecurityRequirement(document =>
            {
                var requirement = new OpenApiSecurityRequirement
                {
                    [new OpenApiSecuritySchemeReference("Bearer", document)] = []
                };
                return requirement;
            });
        });
        
        return services;
    }
}
